### ISSUE TITLE
Allow setting default window with 0 as default

### ISSUE THREAD

**Issue by ndarilek** [minhajuddin/tummy#1]
Thanks for this! Not a huge fan of tmuxinator's global list of projects.

One minor frustration I'm experiencing is that I set up window 0 as an editor/server window, with windows 1+ for auxiliary tasks. Whenever I launch a session, I'm always dropped into the last window I create.

Is there some way to set a default window? It might also be nice to default to window 0 if one isn't set, since I'd assume 0 is where most main tasks are run. I suppose this might break if the window index is set to 1, so I'm not immediately sure how to handle that. New to tmux.

Thanks!

**Comment by minhajuddin** [comment]
Glad that you like this :slightly_smiling_face: 

It should be selecting the first window (index 0) when you initially run tummy. If you look at the debug messages it runs this `tmux select-window -t session_name:0` right before it attaches to the session. Adding an option to override this also sounds like a good idea.

Can you paste your Tmuxfile and the messages printed on the terminal when you start and disconnect from your tmux session (cd project; tummy; Ctrl+d)

**Comment by ndarilek** [comment]
Not sure what happened, but you're right, the first window was default. 
Somehow I created a session and landed in the last window created, 
though I may be misremembering what happened and can't duplicate the 
problem in any case.

Thanks for the new feature!Y
